name: InstantCommandLoader
path: src/chell_uoxou/main.php
main: InstantCommandLoader\ICL
version: 0.2.3
api: 1.6.4_Dev
load: STARTUP
author: chell_uoxou
description: Load php files to add PHPPO command.
commands:
 icl:
  permission: icl.command
  usage: "icl <reload|add|del> <name> <path>"
permissions:
 icl.command:
  default: root
  description: "allow all command"
